variables:
  NODE_CACHE_DIR: node_modules/

stages:
  - dependencies
  - codequality
  - containerize

# As the k8s runner does not support cache yet, we need to use artifacts :(
node_modules:
  stage: dependencies
  image: node:16
  artifacts:
    paths:
      - $NODE_CACHE_DIR
    expire_in: 30 minutes
  script:
    - '[ -d $NODE_CACHE_DIR ] && [ ! -z "$(ls -A $NODE_CACHE_DIR)" ] || npm ci'

eslint:
  stage: codequality
  image: node:16
  dependencies:
    - node_modules
  script:
    - npm run lint

build_image:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - when: manual
  dependencies:
    - node_modules
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"},\"$HARBOR_HOST\":{\"username\":\"$HARBOR_USERNAME\",\"password\":\"$HARBOR_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - sed -i '/^node_modules\/$/d' .dockerignore
    - /kaniko/executor
      --context     "$CI_PROJECT_DIR"
      --dockerfile  "$CI_PROJECT_DIR/Dockerfile.kaniko"
      --destination "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      --destination "$HARBOR_HOST/$HARBOR_PROJECT/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG"
      --target      "production"
